apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-gl-saas-vyr0ppnt234ic
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component-gl-saas-vyr0ppnt234ic
    app.kubernetes.io/part-of: application-gl-saas-tgpyjo5qosawy
  name: component-gl-saas-vyr0ppnt234ic
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: go-app
    app.kubernetes.io/instance: component-gl-saas-vyr0ppnt234ic
status:
  loadBalancer: {}
